### ISSUE TITLE
redactor-rails with AWS S3 buckets

### ISSUE THREAD

**Issue by ghvillasboas** [SammyLin/redactor-rails#109]
Is it possible to get this gem working with a AWS S3 bucket for image uploads? I can successfully upload and manipulate files directly on the Rails Models using carrierwave/fog, but having a hard time to make Redactor to list and upload files to S3.

Already tried the example provided by the Imperavi guys (http://imperavi.com/redactor/examples/s3/) but no progress with Redactor-Rails. Any insights?

Best.

**Comment by dangodev** [comment]
It should work if you change

```
storage :file
```
to
```
storage :fog
```
in the `app/uploaders` uploaders.
