### ISSUE TITLE
Conflict with TurboLinks

### ISSUE THREAD

**Issue by jsandlund** [SammyLin/redactor-rails#118]
Hi, 

Redactor doesn't display on first page-load when turbolinks is active. Upon page load, it properly renders. Disabling turbolinks on the "body" element fixes this issue. 

- Load new page: redactor does not load. 
- Refresh page: redactor loads. 
- Disabling turbolinks fixes the issue. 

Thoughts on the root cause? Form code below. 

<%= form_for @article do |f| %>
	
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<% if @article.errors.any? %>
					<h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>		
					<ul>
					<% @article.errors.full_messages.each do |msg| %>
						<li> <%= msg %></li>
					<% end %>
					</ul>	
				<% end %>
			</div>
		</div>
	</div>
	
	<p class="text-center">
		<%= f.label :title %><br>
	  <%= f.text_field :title %>
	</p>
	
	<div class="container">
		<div class="row">
			<div class="redactor-box col-md-12">
			  <%= f.text_area :text, :class =>"redactor" %>
			</div>
		</div>
	</div>

	<p>
		<%= f.label :featured %>?<br>
	  <%= f.check_box :featured %> yes
	</p>

	<p><%= f.submit %></p>
<% end %>

**Comment by wilgoszpl** [comment]
This issue is solved in new version of redactor-rails.
