### ISSUE TITLE
Recursive redactor box

### ISSUE THREAD

**Issue by wakakokorosensei** [SammyLin/redactor-rails#138]
Hello I'm relatively new in RoR, recently I put redactor-rails in my project test, but I have an issue.
 I start my page with one redactor box, after save the content I want to create another text with redactor, but  I have two redactor boxes in the same page, and this is recursive every time I save the content, I return to create another text I have one more redactor box.

I have this lib
ruby 2.0
rails 4.1.8
bootstrap 3.3.4

![image](https://cloud.githubusercontent.com/assets/11088487/7683117/350d3c5c-fd7d-11e4-8792-3d6828a960db.png)

thank  you very much

**Comment by luaysuarna** [comment]
Hi Guy,
I think that issue because turbolinks, or you call redactor more a time.
And If you want to override redactor, please still on redactor assets > javascript > redactor-rails > config.js

**Comment by wakakokorosensei** [comment]
Hello guy, yes you were right, I take off this line 
//= require turbolinks 
in application.js and now redactor works perfect. But I think this is a problem with turbolinks and bootstrap
Thank you very much for help me,
