### ISSUE TITLE
How to update redactor.js to last version?

### ISSUE THREAD

**Issue by napster3000** [SammyLin/redactor-rails#142]
I have Redactor v10.0.4, how to update to latest version?
Should I do it manually? How?

**Comment by luaysuarna** [comment]
You can update with override file gem.
Just put your new redactor to
redactor-rails/vendor/assets/javascripts/redactor-rails/

**Comment by wilgoszpl** [comment]
Of course if you have the licensed files bought. The redactor files inside of gem files will not be upgraded anymore and when I'll find some time, current files will be downgraded to the latest free version.
