### ISSUE TITLE
How to add class to images added in the redactor?

### ISSUE THREAD

**Issue by suramai** [SammyLin/redactor-rails#144]
Hi. I would like to add class="img-responsive" to all the images inserted using the redactor editor.
Can anyone share how to do that? Kindly help. Thanks.

**Comment by napster3000** [comment]
$(document).ready(
  function(){
  var csrf_token = $('meta[name=csrf-token]').attr('content');
  var csrf_param = $('meta[name=csrf-param]').attr('content');
  var params;
  if (csrf_param !== undefined && csrf_token !== undefined) {
    params = csrf_param + "=" + encodeURIComponent(csrf_token);
  }
  $('.redactor').redactor(
    { "imageUpload":"/redactor_rails/pictures?" + params,
      "imageGetJson":"/redactor_rails/pictures",
      "fileUpload":"/redactor_rails/documents?" + params,
      "fileGetJson":"/redactor_rails/documents",
      "path":"/assets/redactor-rails",
      "css":"style.css",
      "plugins": ['video'],
      fileUploadErrorCallback: function(json)
      {
          alert(json['error']['data'][1]);
      },
      imageUploadCallback: function(image, json)
      {
        image.addClass('img-responsive')
      }
    }
  );
});

**Comment by suramai** [comment]
@napster3000 That worked like a charm. Perfect. Thank you sooooooooooo much.
