### ISSUE TITLE
Redactor II

### ISSUE THREAD

**Issue by ahmetabdi** [SammyLin/redactor-rails#153]
Does this gem have plans of moving over to redactor V2, released on October 11th 2015. http://imperavi.com/redactor/log/

This gem is lagging behind with the version `10.0.4` which was released in November 10th, 2014.

**Comment by zachrnolan** [comment]
Would love to see this +1

**Comment by andiruleu** [comment]
same here +1

**Comment by jaymiejones86** [comment]
Would be awesome to see this gem update to v2
On Sun, 13 Dec 2015 at 1:23 PM, andiruleu <notifications@github.com> wrote:

> same here +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SammyLin/redactor-rails/issues/153#issuecomment-164212222>
> .
>
-- 
Jaymie Jones
@pixelstackcom
http://jaymiejonesphoto.com
http://codercatchup.com
https://devbase.io

**Comment by SammyLin** [comment]
Unfortunately, I can't upgrade it , because Redactor has license.
In order to not conflict with the law, so I can not upgrade

**Comment by StarWar** [comment]
So, If I purchase license and include js and css from redactor II. Can it work or will it cause my existing setup to break?
