### ISSUE TITLE
File button on the toolbar

### ISSUE THREAD

**Issue by eliaswebdev** [SammyLin/redactor-rails#45]
Hi. How can I add the file button on the toolbar?
I tried insert into my redactor-rails/config.js the line:

'buttons': ['html', '|', 'formatting', '|', 'bold', 'italic', 'deleted', '|', 'unorderedlist', 'orderedlist', 'outdent', 'indent', '|', 'image', 'video', 'file', 'table', 'link', '|', 'fontcolor', 'backcolor', '|', 'alignment', '|', 'horizontalrule']

Everything works correctly but the file button does not work.
Can you help-me?

**Comment by satansdeer** [comment]
@eliaswebdev wtf man! When you solve problem you don't just say "I solved"! Tell us how did you solve it!
