### ISSUE TITLE
undefined method `authenticate_user!' for #

### ISSUE THREAD

**Issue by artisr** [SammyLin/redactor-rails#57]
Hi.. I get a following error when i try to upload images using redactor rails:

NoMethodError in RedactorRails::PicturesController#index

undefined method `authenticate_user!' for # RedactorRails::PicturesController:0x000000050028f0>

here's the full trace: https://gist.github.com/ArtisR/ab5628972051a0a846cb

**Comment by amitfriedman12** [comment]
I added this line to my controller which did the trick for me:
```
    include Devise::Controllers::Helpers
```
