### ISSUE TITLE
How to add a plugin FontSize?

### ISSUE THREAD

**Issue by araslanov-e** [SammyLin/redactor-rails#77]
Add file fontsize.js, and
Object #<Object> has no method 'buttonAdd'
for
this.buttonAdd( 'fontsize', 'Change font size', false, dropdown)

**Comment by wilgoszpl** [comment]
I updated all supported plugins.

I'm not sure what caused the problem when you created this issue, but currently, after updating redactor editor, all you need to do is follow documentation here: https://github.com/SammyLin/redactor-rails#using-plugins 

When I'm writing this comment, version of redactor-rails included this fix is not published to rubygems, so you should specify github: 'sammylin/redactor-rails' in your gemfile
