### ISSUE TITLE
>>Uncaught TypeError: Cannot read property '0' of null<< while uploading image on production

### ISSUE THREAD

**Issue by Averethel** [SammyLin/redactor-rails#83]
When I'm trying to upload image on staging server I keep getting ```Uncaught TypeError: Cannot read property '0' of null``` javascript error.
On development everything works just fine so that's quite weird. I checked that no request have been made so it's even weirder.

I use rails 4.0 and ruby 2.0.

**Comment by jennycodes** [comment]
@Averethel @pascalbetz @nardstae I know this is years later, but I just had the same problem in development. Did anyone resolve this?

**Comment by pascalbetz** [comment]
No, not even sure the project where we used the lib is still active.

**Comment by Averethel** [comment]
As we wrote - the problem was imagemagick was not installed on the machine.
