### ISSUE TITLE
Asset pipeline ignores custom config.js. Only the gem's config.js is being loaded

### ISSUE THREAD

**Issue by hoenth** [SammyLin/redactor-rails#87]
I have installed and configured redactor-rails, and in development, it works perfectly, including several plugins, and changing the buttons.

However, when i push to our beta servers, using precompiled assets delivered via the asset pipeline, only the config.js from the gem appears. 

Reading up on this a bit, there is a discussion of how to overwrite specific gem asset files here: http://stackoverflow.com/questions/16435428/rails-how-to-override-single-files-from-gem-assets-for-assetsprecompile-solv

I didn't see any wizardry within the redactor-rails gem that would lead me to believe that the above is not necessary, but also assume that I am not the first person to deploy redactor-rails with a custom config.js file either. 

Have others not had this issue? Is there a work around I am missing?

Tom

**Comment by StarWar** [comment]
For me it says "Cannot read property 'set' of undefined"
