### ISSUE TITLE
Bundling redactor distributions breaks license

### ISSUE THREAD

**Issue by wyaeld** [SammyLin/redactor-rails#98]
While I admire the work you're putting in, including the redactor distributions themselves is breaking Imperavi's licensing.

http://imperavi.com/redactor/faq/#q3

> However, keep in mind that Redactor is not an open-source product. It is proprietary commercial copyrighted software and we do not allow it's distribution under any open- source licenses. Think about Redactor as if it was a paid proprietary extension for 
your project.

http://imperavi.com/redactor/license/

Essentially, you are allowed to do whatever you want with redactor in your own product, but you aren't allowed to become a distributor of the library itself, as you are doing here.

I don't work for Imperavi, I'm actually just a customer of theirs, and I think they do great work.  But Imperavi isn't a big company, its only a few people, and paying them for an appropriate license (its a small one-time purchase) so you can use their software, and they can keep working on it, is an excellent deal.

You can't just MIT license a project, which is bundling and distributing someone elses commercial work.  It doesn't work like that.

**Comment by wilgoszpl** [comment]
@wyaeld  I have written directly to Imperavi about that. It wasn't our goal to break their license, it was just our oversight. Thanks for heads up!

**Comment by wilgoszpl** [comment]
I got an answer from Imperavi - probably redactor Code will be removed completely from whole git repository.

**Comment by wyaeld** [comment]
@wilgoszpl you're welcome.  Sorry it resulted in the overall removal.

I've seen other projects successfully ship with a different editor, but explain that redactor is preferred, and give the install instructions.

For our purposes, we just buy a license for unlimited use.  Hard to find another organisation out there that offers lifetime updates off a single license, and then ships new versions every month.  I want these guys to stay around for a long time.

**Comment by jaymiejones86** [comment]
So if redactor is being removed completely from git, will we simply be required to integrate redactor ourselves and use the gem for the Carrierwave support and general customisation?











Kind regards,  -- 
 Jaymie Jones

@pixelstackcom

http://pixelstack.com
http://jaymiejonesphoto.com

**Comment by wilgoszpl** [comment]
@wyaeld , buying OEM license will not work in this project - the application needs to be something more than simple rails integration to include redactor as open source.

**Comment by wilgoszpl** [comment]
@jaymiejones86 , we decided to downgrade redactor files to latest free-to-use version (8.2.2) . Those files will be included in redactor-rails, but every newest update needs to be removed.

Yes, we will be required to integrate redactor files ourselves (copying files should be enough)  - I'll add a note about that to README soon.
